[functions.stripe-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/stripe-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/stripe-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/stripe-webhook/*.html" ]


[functions.create-stripe-checkout]
enabled = true
verify_jwt = false
import_map = "./functions/create-stripe-checkout/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-stripe-checkout/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-stripe-checkout/*.html" ]

[functions.save-apple-external-purchase-tokens]
enabled = true
verify_jwt = false
import_map = "./functions/save-apple-external-purchase-tokens/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/save-apple-external-purchase-tokens/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/save-apple-external-purchase-tokens/*.html" ]

[functions.report-expired-apple-tokens]
enabled = true
verify_jwt = false
entrypoint = "./functions/report-expired-apple-tokens/index.ts"

[functions.apple-server-notifications]
enabled = true
verify_jwt = false
entrypoint = "./functions/apple-server-notifications/index.ts"
static_files = [ "./functions/apple-server-notifications/certs/*.cer" ]
